### PR TITLE
Added missing functions from libusb.h

### LINKED ISSUE #19: libusb_fill_bulk_transfer
I see `libusb_fill_bulk_transfer` isn't wrapped here. I'm wondering if we can add it and associated other functions if also missing.

Being able to use `libusb_fill_bulk_transfer`  and `libusb_submit_transfer` + `libusb_alloc_transfer` upstream in `rusb` would make things a lot easier to manage better throughput in transfers.

I found this [doc](https://elinux.org/images/a/ae/Ott--usb_and_the_real_world.pdf) provided some good explanations in a concise way.

### PR DESCRIPTION
**Pull request by a1ien**
Fix #19

### CODE REVIEW

**Comment by ianrrees** [comment]
This looks great, @a1ien , thanks!

**Comment by ianrrees** [comment]
Sorry to bother you about this @a1ien , but I just went to update my project to use this and noticed that the version isn't changed, I guess it needs a minor version bump.  No rush from my end, I'm happy to keep using my local workaround in the mean time.

**Comment by a1ien** [comment]
I plan to publish a new version in the next couple of days

**Comment by a1ien** [comment]
Done.

**Pull request merged**
